# Generated by Django 4.1.2 on 2023-05-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MapSection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
